name: gitops actions
on: workflow_dispatch
env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: gitops-app
  EKS_CLUSTER: gitops-cluster

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Maven test
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Set Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # - name: Setup SonarQube
      #   uses: warchant/setup-sonar-scanner@v7
        
      # - name: SonarQube Scan
      #   run: |
      #     sonar-scanner  
      #     -Dsonar.host.url=${{ secrets.SONAR_URL }} 
      #     -Dsonar.login=${{ secrets.SONAR_TOKEN }} 
      #     -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} 
      #     -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} 
      #     -Dsonar.sources=src/ 
      #     -Dsonar.junit.reportsPath=target/surefire-reports/ 
      #     -Dsonar.jacoco.reportsPath=target/jacoco.exec 
      #     -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml 
      #     -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/

  BUILD_AND_PUBLISH:
    runs-on: ubuntu-latest
    needs: Testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Upload Image to ECR
        uses: appleboy/docker-ecr-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
          registry: ${{ secrets.REGISTRY }}
          repo: ${{ env.ECR_REPOSITORY }}
          tags: latest, ${{ github.run_number }}
          daemon_off: false
          dockerfile: ./Dockerfile
          context: ./